M48
; DRILL file {KiCad 7.0.6} date Thu Aug 10 11:03:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-10T11:03:09+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X6.6644Y-4.7638
X6.6644Y-4.937
T2
X4.6809Y-1.7285
X4.6809Y-2.5947
X5.547Y-1.7285
X5.547Y-2.5947
T0
M30
